name: Periodic

on:
  schedule:
  - cron: 0 11 * * ?

jobs:
  build:

    strategy:
      matrix:
        os: [ubuntu-latest]
        rust: [stable]

    runs-on: ${{ matrix.os }}

    steps:
    - name: Checkout
      uses: actions/checkout@v1
