name: Periodic

on:
  schedule:
  - cron: 0 11 * * ?

jobs:
  linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
#      - name: Install dependencies
#        run: sudo apt-get install ...
      - name: Run regression test
        run: source regress.sh

  mac:
    runs-on: macOS-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
#      - name: Install dependencies
#        run: brew install ...
      - name: Run regression test
        run: source regress.sh
